# Build stage
FROM node:18.14.0 as build-stage

WORKDIR /usr/src

# Copy package.json and package-lock.json
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the application source code
COPY . .

# Build the Angular application
RUN npm run build --prod



# Compiled app based on nginx
FROM nginx:1.19
COPY --from=build-stage /usr/src/dist/angular-reactive/ /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 1827
